### ISSUE TITLE
文档中对接SSPanel Custom Config 示例中alter_id未加引号

### ISSUE THREAD

**Issue by 0w0zhihe** [XrayR-project/XrayR-doc#6]
tcp示例
{
    "offset_port_node": "12345",
    "server_sub": "hk.domain.com",
    "alter_id": 0,
    "network": "tcp",
    "security": "none"
}

应为

tcp示例
{
    "offset_port_node": "12345",
    "server_sub": "hk.domain.com",
    "alter_id": "0",
    "network": "tcp",
    "security": "none"
}
其他均同，具体可见SSpanel文档https://wiki.sspanel.org/#/custom-config，不加引号将导致后端对接报错

**Comment by 0w0zhihe** [comment]
SSpanel文档：https://wiki.sspanel.org/#/custom-config

**Comment by pocketW** [comment]
Fixed at #4
